version: "3.8"
services:
  config-server-1:
    container_name: config-server-1
    image: mongo:6
    command: mongod --configsvr --replSet config-server --port 27017 --dbpath /data/db
    ports:
      - 40001:27017
    volumes:
      - config-server-1:/data/db

  config-server-2:
    container_name: config-server-2
    image: mongo:6
    command: mongod --configsvr --replSet config-server --port 27017 --dbpath /data/db
    ports:
      - 40002:27017
    volumes:
      - config-server-2:/data/db

  config-server-3:
    container_name: config-server-3
    image: mongo:6
    command: mongod --configsvr --replSet config-server --port 27017 --dbpath /data/db
    ports:
      - 40003:27017
    volumes:
      - config-server-3:/data/db

  shard1-server-1:
    container_name: shard1-server-1
    image: mongo:6
    command: mongod --shardsvr --replSet shard1 --port 27017 --dbpath /data/db
    ports:
      - 50001:27017
    volumes:
      - shard1-server-1:/data/db

  shard1-server-2:
    container_name: shard1-server-2
    image: mongo:6
    command: mongod --shardsvr --replSet shard1 --port 27017 --dbpath /data/db
    ports:
      - 50002:27017
    volumes:
      - shard1-server-2:/data/db

  shard1-server-3:
    container_name: shard1-server-3
    image: mongo:6
    command: mongod --shardsvr --replSet shard1 --port 27017 --dbpath /data/db
    ports:
      - 50003:27017
    volumes:
      - shard1-server-3:/data/db

  shard2-server-1:
    container_name: shard2-server-1
    image: mongo:6
    command: mongod --shardsvr --replSet shard2 --port 27017 --dbpath /data/db
    ports:
      - 50004:27017
    volumes:
      - shard2-server-1:/data/db

  shard2-server-2:
    container_name: shard2-server-2
    image: mongo:6
    command: mongod --shardsvr --replSet shard2 --port 27017 --dbpath /data/db
    ports:
      - 50005:27017
    volumes:
      - shard2-server-2:/data/db

  shard2-server-3:
    container_name: shard2-server-3
    image: mongo:6
    command: mongod --shardsvr --replSet shard2 --port 27017 --dbpath /data/db
    ports:
      - 50006:27017
    volumes:
      - shard2-server-3:/data/db

  mongos-router:
    container_name: mongos-router
    image: mongo:6
    command: mongos --configdb config-server/config-server-1:27017,config-server-2:27017,config-server-3:27017 --bind_ip_all --port 27017
    ports:
      - 60000:27017

volumes:
  config-server-1: {}
  config-server-2: {}
  config-server-3: {}
  shard1-server-1: {}
  shard1-server-2: {}
  shard1-server-3: {}
  shard2-server-1: {}
  shard2-server-2: {}
  shard2-server-3: {}
